[package]
name = "engine-q"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"crates/nu-cli",
	"crates/nu-engine",
	"crates/nu-parser",
	"crates/nu-command",
	"crates/nu-protocol",
	"crates/nu-plugin",
	"crates/nu-dataframe",
	"crates/nu_plugin_inc",
]

[dependencies]
reedline = { git = "https://github.com/nushell/reedline", branch = "main" }
crossterm = "0.22.*"
dialoguer = "0.9.0"
nu-cli = { path="./crates/nu-cli" }
nu-command = { path="./crates/nu-command" }
nu-engine = { path="./crates/nu-engine" }
nu-json = { path="./crates/nu-json" }
nu-parser = { path="./crates/nu-parser" }
nu-path = { path="./crates/nu-path" }
nu-protocol = { path = "./crates/nu-protocol" }
nu-plugin = { path = "./crates/nu-plugin", optional = true }
nu-table = { path = "./crates/nu-table" }
nu-term-grid = { path = "./crates/nu-term-grid" }
miette = "3.0.0"
ctrlc = "3.2.1"
# mimalloc = { version = "*", default-features = false }

[features]
plugin = ["nu-plugin", "nu-parser/plugin", "nu-command/plugin", "nu-protocol/plugin"]
custom = ["nu-command/custom", "nu-protocol/custom"]
dataframe = ["nu-command/dataframe"]
default = ["plugin", "custom", "dataframe"]

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.7"
pretty_assertions = "0.7.2"
