[package]
name = "nu-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-protocol = { path = "../nu-protocol", features = ["plugin"] }
nu-path = { path = "../nu-path" }
itertools = "0.10.1"
chrono = { version="0.4.19", features=["serde"] }
glob = "0.3.0"

[features]
plugin = []
