[package]
authors = ["The Nu Project Contributors"]
description = "Nushell table printing"
edition = "2018"
license = "MIT"
name = "nu-table"
version = "0.36.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "table"
path = "src/main.rs"

[dependencies]
# nu-ansi-term = { path = "../nu-ansi-term" }
nu-ansi-term = "0.39.0"
nu-protocol = { path = "../nu-protocol"}
regex = "1.4"
unicode-width = "0.1.8"
strip-ansi-escapes = "0.1.1"
ansi-cut = "0.1.1"
atty = "0.2.14"
