[package]
name = "nu-plugin"
version = "0.1.0"
edition = "2018"

[dependencies]
capnp = "0.14.3"
nu-protocol = { path = "../nu-protocol" }
nu-engine = { path = "../nu-engine" }
serde = {version = "1.0.130", features = ["derive"]}
serde_json = { version = "1.0"}



