[package]
name = "nu-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = "3.0.0"
thiserror = "1.0.29"
serde_json = "1.0"
nu-path = {path = "../nu-path"}
nu-protocol = { path = "../nu-protocol"}
nu-plugin = { path = "../nu-plugin", optional = true }
log = "0.4"

[features]
plugin = ["nu-plugin"]
