[package]
name = "nu-command"
version = "0.1.0"
edition = "2018"
build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-engine = { path = "../nu-engine" }
nu-json = { path = "../nu-json" }
nu-path = { path = "../nu-path" }
nu-pretty-hex = { path = "../nu-pretty-hex" }
nu-protocol = { path = "../nu-protocol" }
nu-table = { path = "../nu-table" }
nu-term-grid = { path = "../nu-term-grid" }
nu-parser = { path = "../nu-parser" }
# nu-ansi-term = { path = "../nu-ansi-term" }
nu-ansi-term = "0.42.0"
nu-color-config = { path = "../nu-color-config" }

# Potential dependencies for extras
url = "2.2.1"
csv = "1.1.3"
glob = "0.3.0"
Inflector = "0.11"
thiserror = "1.0.29"
sysinfo = "0.22.2"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
chrono-tz = "0.6.0"
dtparse = "1.2.0"
terminal_size = "0.1.17"
indexmap = { version="1.7", features=["serde-1"] }
lscolors = { version = "0.8.0", features = ["crossterm"] }
bytesize = "1.1.0"
dialoguer = "0.9.0"
rayon = "1.5.1"
regex = "1.5.4"
titlecase = "1.1.0"
meval = "0.2.0"
serde = { version="1.0.123", features=["derive"] }
serde_yaml = "0.8.16"
serde_urlencoded = "0.7.0"
serde_ini = "0.2.0"
eml-parser = "0.1.0"
toml = "0.5.8"
itertools = "0.10.0"
ical = "0.7.0"
calamine = "0.18.0"
roxmltree = "0.14.0"
rand = "0.8"
rust-embed = "6.3.0"
trash = { version = "2.0.2", optional = true }
unicode-segmentation = "1.8.0"
uuid = { version = "0.8.2", features = ["v4"] }
htmlescape = "0.3.1"
zip = { version="0.5.9", optional=true }
lazy_static = "1.4.0"
strip-ansi-escapes = "0.1.1"
crossterm = "0.22.1"
shadow-rs = "0.8.1"
quick-xml = "0.22"
digest = "0.10.0"
md5 = { package = "md-5", version = "0.10.0" }
sha2 = "0.10.0"
base64 = "0.13.0"
encoding_rs = "0.8.30"
num = { version = "0.4.0", optional = true }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
reqwest = {version = "0.11", features = ["blocking"], optional = true }
mime = "0.3.16"

[target.'cfg(unix)'.dependencies]
umask = "1.0.0"
users = "0.11.0"

[dependencies.polars]
version = "0.18.0"
optional = true
features = [
	"default", "parquet", "json", "serde", "object",
	"checked_arithmetic", "strings", "cum_agg", "is_in",
	"rolling_window", "strings", "pivot", "random"
]

[features]
trash-support = ["trash"]
plugin = ["nu-parser/plugin"]
dataframe = ["polars", "num"]
fetch = ["reqwest", "tokio"]

[build-dependencies]
shadow-rs = "0.8.1"
